# fly.toml app configuration file generated for efilm-api-project on 2023-08-12T23:57:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "efilm-api-project"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
